name: Actions Status Discord
on : [push]
jobs:
  Discord-Notify:
    runs-on: ubuntu-latest
    steps:
      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@v1.13.0
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
