name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
      - name: Run reviewdog with golint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: golint ./... | reviewdog -reporter=github-pr-check -f=golint
      - name: Run reviewdog with govet
        run: go vet ./... 2>&1 | reviewdog -reporter=github-pr-check -f=govet
