name: File Create
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: file download and diff 
        run: |
           wget https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv &&
           /usr/bin/diff ./syukujitsu.csv ./csv/syukujitsu.csv > diff1.log || true && 
           /usr/bin/diff ./syukujitsu.csv ./csv/syukujitsu_utf8.csv > diff2.log || true

      - name: show diff
        run: |
           cat ./diff*

      - name: file remove
        run: |
           rm ./diff*
           rm ./syukujitsu.csv
