name: File Create
on:
  push:
    branches:
      - main

jobs:
  check_diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: file download and diff 
        id: diff
        run: |
           wget https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv &&
           /usr/bin/diff ./syukujitsu.csv ./csv/syukujitsu.csv

      - name: echo success
        if: steps.diff.outcome == 'success'
        run: echo "success"
